name: merge_PR

on:
  pull_request:
    branches: [master]
    types: [opened]
    
 # workflow_run:
   # types:
     # - completed
   # workflows:
      # List all required workflow names here.
      #- 'Continuous Integration'
      
  #check_suite:
   # types:
    # - completed


jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: show
        run: git rev-parse HEAD
        
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "rebase"
          MERGE_COMMIT_MESSAGE: "Auto merge ${{ github.event.pull_request.number }}"
